services:
  db:
    image: sqlite3
    volumes:
      - ./tmp/db:/var/lib/sqlite3/data
    environment:
      POSTGRES_PASSWORD: password
  redis:
    image: redis:latest
    ports:
    - "6379:6379"
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/price_alert
    ports:
      - "3000:3000"
    # depends_on:
    #   - db
    #   - redis


# services:
#   db:
#     image: postgres
#     volumes:
#       - ./tmp/db:/var/lib/postgresql/data
#     environment:
#       POSTGRES_PASSWORD: password
#   web:
#     build: .
#     command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
#     volumes:
#       - .:/myapp
#     ports:
#       - "3000:3000"
#     # depends_on:
#     #   - db
